local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function(opts)
    local c = require('vlt.colors').get_colors()
    local isDark = vim.o.background == 'dark'

    hl(0, 'Normal', { fg = c.Front, bg = c.Back })
    hl(0, 'ColorColumn', { fg = 'NONE', bg = c.CursorDarkDark })
    hl(0, 'Cursor', { fg = c.CursorDark, bg = c.CursorLight })
    hl(0, 'CursorLine', { bg = c.CursorDarkDark })
    hl(0, 'CursorColumn', { fg = 'NONE', bg = c.CursorDarkDark })
    hl(0, 'Directory', { fg = c.Blue, bg = c.Back })
    hl(0, 'DiffAdd', { fg = c.Green, bg = c.CursorDarkDark })
    hl(0, 'DiffChange', { fg = 'NONE', bg = c.DiffRedDark })
    hl(0, 'DiffDelete', { fg = c.Red, bg = c.CursorDarkDark })
    hl(0, 'DiffText', { fg = 'NONE', bg = c.DiffRedLight })
    hl(0, 'EndOfBuffer', { fg = c.Back, bg = 'NONE' })
    hl(0, 'ErrorMsg', { fg = c.Red, bg = c.Back })
    hl(0, 'VertSplit', { fg = c.SplitDark, bg = c.Back })
    hl(0, 'WinSeparator', { link = 'VertSplit' })
    hl(0, 'Folded', { fg = 'NONE', bg = c.FoldBackground })
    hl(0, 'FoldColumn', { fg = c.LineNumber, bg = c.Back })
    hl(0, 'SignColumn', { fg = 'NONE', bg = c.Back })
    hl(0, 'IncSearch', { fg = c.None, bg = c.Selection })
    hl(0, 'LineNr', { fg = c.LineNumber, bg = c.Back })
    hl(0, 'CursorLineNr', { fg = c.Orange, bg = c.Back })
    hl(0, 'MatchParen', { fg = c.None, bg = c.Selection })
    hl(0, 'ModeMsg', { fg = c.Front, bg = c.LeftDark })
    hl(0, 'MoreMsg', { fg = c.Front, bg = c.LeftDark })
    hl(0, 'NonText', { fg = (isDark and c.LineNumber or c.TabOther), bg = c.None })
    hl(0, 'Pmenu', { fg = c.PopupFront, bg = c.PopupBack })
    hl(0, 'PmenuSel', { fg = isDark and c.PopupFront or c.Back, bg = c.PopupHighlightBlue })
    hl(0, 'PmenuSbar', { fg = 'NONE', bg = c.PopupHighlightGray })
    hl(0, 'PmenuThumb', { fg = 'NONE', bg = c.PopupFront })
    hl(0, 'Question', { fg = c.Blue, bg = c.Back })
    hl(0, 'Search', { fg = c.None, bg = c.Selection })
    hl(0, 'SpecialKey', { fg = c.Blue, bg = c.None })
    hl(0, 'StatusLine', { fg = c.Front, bg = c.LeftMid })
    hl(0, 'StatusLineNC', { fg = c.Front, bg = opts.transparent and c.Back or c.LeftDark })
    hl(0, 'TabLine', { fg = c.Front, bg = c.TabOther })
    hl(0, 'TabLineFill', { fg = c.Front, bg = c.TabOutside })
    hl(0, 'TabLineSel', { fg = c.Front, bg = c.TabCurrent })
    hl(0, 'Title', { fg = c.None, bg = c.None, bold = true })
    hl(0, 'Visual', { fg = c.None, bg = c.Selection })
    hl(0, 'VisualNOS', { fg = c.None, bg = c.Selection })
    hl(0, 'WarningMsg', { fg = c.Red, bg = c.Back, bold = true })
    hl(0, 'WildMenu', { fg = c.None, bg = c.Selection })
    hl(0, 'Comment', { fg = c.Gray, bg = 'NONE', italic = opts.italic_comments })
    hl(0, 'Constant', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'String', { fg = c.Green, bg = 'NONE' })
    hl(0, 'Character', { fg = c.Green, bg = 'NONE' })
    hl(0, 'Number', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'Boolean', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'Float', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'Identifier', { fg = c.Front, bg = 'NONE' })
    hl(0, 'Function', { fg = c.Red, bg = 'NONE' })
    hl(0, 'Statement', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'Conditional', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'Repeat', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'Label', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'Operator', { fg = c.Front, bg = 'NONE' })
    hl(0, 'Keyword', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'Exception', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'PreProc', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'Include', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'Define', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'Macro', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'Type', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'StorageClass', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'Structure', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'Typedef', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'Special', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, 'SpecialChar', { fg = c.Front, bg = 'NONE' })
    hl(0, 'Tag', { fg = c.Front, bg = 'NONE' })
    hl(0, 'Delimiter', { fg = c.Front, bg = 'NONE' })
    hl(0, 'SpecialComment', { fg = c.Gray, bg = 'NONE' })
    hl(0, 'Debug', { fg = c.Front, bg = 'NONE' })
    hl(0, 'Underlined', { fg = c.None, bg = 'NONE', underline = true })
    hl(0, 'Conceal', { fg = c.Front, bg = c.Back })
    hl(0, 'Ignore', { fg = c.Front, bg = 'NONE' })
    hl(0, 'Error', { fg = c.Red, bg = c.Back, undercurl = true, sp = c.Red })
    hl(0, 'Todo', { fg = c.YellowOrange, bg = c.Back, bold = true })
    hl(0, 'SpellBad', { fg = c.Red, bg = c.Back, undercurl = true, sp = c.Red })
    hl(0, 'SpellCap', { fg = c.Red, bg = c.Back, undercurl = true, sp = c.Red })
    hl(0, 'SpellRare', { fg = c.Red, bg = c.Back, undercurl = true, sp = c.Red })
    hl(0, 'SpellLocal', { fg = c.Red, bg = c.Back, undercurl = true, sp = c.Red })
    hl(0, 'Whitespace', { fg = isDark and c.LineNumber or c.TabOther })

    -- Treesitter
    hl(0, '@error', { fg = c.Red, bg = 'NONE' })
    hl(0, '@punctuation.bracket', { fg = c.Front, bg = 'NONE' })
    hl(0, '@punctuation.special', { fg = c.Front, bg = 'NONE' })
    hl(0, '@comment', { fg = c.Gray, bg = 'NONE', italic = opts.italic_comments })
    hl(0, '@string.documentation', { fg = c.Gray, bg = 'NONE', italic = opts.italic_comments })
    hl(0, '@constant', { fg = c.Blue, bg = 'NONE' })
    hl(0, '@constant.builtin', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, '@constant.macro', { fg = c.Blue, bg = 'NONE' })
    hl(0, '@string.regex', { fg = c.Orange, bg = 'NONE' })
    hl(0, '@string', { fg = c.Green, bg = 'NONE' })
    hl(0, '@character', { fg = c.Orange, bg = 'NONE' })
    hl(0, '@number', { fg = c.Orange, bg = 'NONE' })
    hl(0, '@boolean', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, '@float', { fg = c.Orange, bg = 'NONE' })
    hl(0, '@annotation', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'decorated_definition.decorator', { fg = c.Orange, bg = 'NONE' })
    hl(0, '@attribute', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, '@attribute.builtin', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, '@namespace', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, '@function.builtin', { fg = c.Red, bg = 'NONE' })
    hl(0, '@function', { fg = c.Red, bg = 'NONE' })
    hl(0, '@function.macro', { fg = c.Red, bg = 'NONE' })
    hl(0, '@parameter', { fg = c.Front, bg = 'NONE' })
    hl(0, '@parameter.reference', { fg = c.Front, bg = 'NONE' })
    hl(0, '@method', { fg = c.Red, bg = 'NONE' })
    hl(0, '@field', { fg = c.Front, bg = 'NONE' })
    hl(0, '@property', { fg = c.Blue, bg = 'NONE' })
    hl(0, '@constructor', { fg = c.Red, bg = 'NONE' })
    hl(0, '@conditional', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, '@repeat', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, '@label', { fg = c.Front, bg = 'NONE' })
    hl(0, '@symbol', { fg = c.Blue, bg = 'NONE' })
    hl(0, '@keyword', { fg = c.Blue, bg = 'NONE' ,bold = true })
    hl(0, '@keyword.function', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, '@keyword.operator', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, '@operator', { fg = c.Front, bg = 'NONE' })
    hl(0, '@exception', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, '@type', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, '@type.builtin', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, '@type.qualifier', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, '@storageClass', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, '@structure', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, '@include', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, '@variable', { fg = c.Front, bg = 'NONE' })
    hl(0, '@variable.builtin', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, '@text', { fg = c.Front, bg = 'NONE' })
    hl(0, '@text.underline', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, '@tag', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, '@tag.delimiter', { fg = c.Gray, bg = 'NONE' })
    hl(0, '@tag.attribute', { fg = c.Red, bg = 'NONE' })

    hl(0, '@text.title', { fg = isDark and c.Blue or c.YellowOrange, bold = true })
    hl(0, '@text.literal', { fg = c.Front, bg = 'NONE' })
    hl(0, '@text.literal.markdown', { fg = c.Orange, bg = 'NONE' })
    hl(0, '@text.literal.markdown_inline', { fg = c.Orange, bg = 'NONE' })
    hl(0, '@text.emphasis', { fg = c.Front, bg = 'NONE', italic = true })
    hl(0, '@text.strike', { fg = c.Front, bg = 'NONE', strikethrough = true })
    hl(0, '@text.strong', { fg = isDark and c.Blue or c.Violet, bold = true })
    hl(0, '@text.uri', { fg = c.Front, bg = 'NONE' })
    hl(0, '@textReference', { fg = isDark and c.Orange or c.YellowOrange })
    hl(0, '@punctuation.delimiter', { fg = c.Front, bg = 'NONE' })
    hl(0, '@stringEscape', { fg = isDark and c.Orange or c.YellowOrange, bold = true })

    hl(0, '@text.note', { fg = c.BlueGreen, bg = 'NONE', bold = true })
    hl(0, '@text.warning', { fg = c.YellowOrange, bg = 'NONE', bold = true })
    hl(0, '@text.danger', { fg = c.Red, bg = 'NONE', bold = true })

    hl(0, '@text.diff.add', { link = 'DiffAdd' })
    hl(0, '@text.diff.delete', { link = 'DiffDelete' })

    -- LSP semantic tokens
    hl(0, '@lsp.typemod.type.defaultLibrary', { link = '@type.builtin' })
    hl(0, '@lsp.type.type', { link = '@type' })
    hl(0, '@lsp.type.typeParameter', { link = '@type' })
    hl(0, '@lsp.type.macro', { link = '@constant' })
    hl(0, '@lsp.type.enumMember', { link = '@constant' })
    hl(0, '@event', { link = 'Identifier' })
    hl(0, '@interface', { link = 'Identifier' })
    hl(0, '@modifier', { link = 'Identifier' })
    hl(0, '@regexp', { fg = c.Red, bg = 'NONE' })
    hl(0, '@decorator', { link = 'Identifier' })

    -- Markdown
    hl(0, 'markdownBold', { fg = isDark and c.Blue or c.YellowOrange, bold = true })
    hl(0, 'markdownCode', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'markdownRule', { fg = isDark and c.Blue or c.YellowOrange, bold = true })
    hl(0, 'markdownCodeDelimiter', { fg = c.Front, bg = 'NONE' })
    hl(0, 'markdownHeadingDelimiter', { fg = isDark and c.Blue or c.YellowOrange, bg = 'NONE' })
    hl(0, 'markdownFootnote', { fg = isDark and c.Orange or c.YellowOrange, bg = 'NONE' })
    hl(0, 'markdownFootnoteDefinition', { fg = isDark and c.Orange or c.YellowOrange })
    hl(0, 'markdownUrl', { fg = c.Front, bg = 'NONE', underline = true })
    hl(0, 'markdownLinkText', { fg = isDark and c.Orange or c.YellowOrange })
    hl(0, 'markdownEscape', { fg = isDark and c.Orange or c.YellowOrange })

    -- Asciidoc
    hl(0, "asciidocAttributeEntry", { fg = c.YellowOrange })
    hl(0, "asciidocAttributeList", { fg = c.Pink })
    hl(0, "asciidocAttributeRef", { fg = c.YellowOrange })
    hl(0, "asciidocHLabel", { fg = c.Blue, bold = true })
    hl(0, "asciidocListingBlock", { fg = c.Orange })
    hl(0, "asciidocMacroAttributes", { fg = c.YellowOrange })
    hl(0, "asciidocOneLineTitle", { fg = c.Blue, bold = true })
    hl(0, "asciidocPassthroughBlock", { fg = c.Blue })
    hl(0, "asciidocQuotedMonospaced", { fg = c.Orange })
    hl(0, "asciidocTriplePlusPassthrough", { fg = c.Yellow })
    hl(0, "asciidocMacro", { fg = c.Pink })
    hl(0, "asciidocAdmonition", { fg = c.Orange })
    hl(0, "asciidocQuotedEmphasized", { fg = c.Blue, italic = true })
    hl(0, "asciidocQuotedEmphasized2", { fg = c.Blue, italic = true })
    hl(0, "asciidocQuotedEmphasizedItalic", { fg = c.Blue, italic = true })
    hl(0, "asciidocBackslash", { link = "Keyword" })
    hl(0, "asciidocQuotedBold", { link = "markdownBold" })
    hl(0, "asciidocQuotedMonospaced2", { link = "asciidocQuotedMonospaced" })
    hl(0, "asciidocQuotedUnconstrainedBold", { link = "asciidocQuotedBold" })
    hl(0, "asciidocQuotedUnconstrainedEmphasized", { link = "asciidocQuotedEmphasized" })
    hl(0, "asciidocURL", { link = "markdownUrl" })

    -- JSON
    hl(0, 'jsonKeyword', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsonEscape', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, 'jsonNull', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'jsonBoolean', { fg = c.Blue, bg = 'NONE' })

    -- HTML
    hl(0, 'htmlTag', { fg = c.Gray, bg = 'NONE' })
    hl(0, 'htmlEndTag', { fg = c.Gray, bg = 'NONE' })
    hl(0, 'htmlTagName', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'htmlSpecialTagName', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'htmlArg', { fg = c.LightBlue, bg = 'NONE' })

    -- PHP
    hl(0, 'phpStaticClasses', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'phpMethod', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'phpClass', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'phpFunction', { fg = c.Red, bg = 'NONE' })
    hl(0, 'phpInclude', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'phpUseClass', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'phpRegion', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'phpMethodsVar', { fg = c.Front, bg = 'NONE' })

    -- CSS
    hl(0, 'cssBraces', { fg = c.Front, bg = 'NONE' })
    hl(0, 'cssInclude', { fg = c.Pink, bg = 'NONE' })
    hl(0, 'cssTagName', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, 'cssClassName', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, 'cssPseudoClass', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, 'cssPseudoClassId', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, 'cssPseudoClassLang', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, 'cssIdentifier', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, 'cssProp', { fg = c.LightBlue, bg = 'NONE' })
    hl(0, 'cssDefinition', { fg = c.LightBlue, bg = 'NONE' })
    hl(0, 'cssAttr', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'cssAttrRegion', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'cssColor', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'cssFunction', { fg = c.Red, bg = 'NONE' })
    hl(0, 'cssFunctionName', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'cssVendor', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'cssValueNumber', { fg = c.Green, bg = 'NONE' })
    hl(0, 'cssValueLength', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'cssUnitDecorators', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'cssStyle', { fg = c.LightBlue, bg = 'NONE' })
    hl(0, 'cssImportant', { fg = c.Blue, bg = 'NONE' })

    -- JavaScript
    hl(0, 'jsVariableDef', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsFuncArgs', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsFuncBlock', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsRegexpString', { fg = c.LightRed, bg = 'NONE' })
    hl(0, 'jsThis', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'jsOperatorKeyword', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'jsDestructuringBlock', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsObjectKey', { fg = c.Fron, bg = 'NONE' })
    hl(0, 'jsGlobalObjects', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'jsModuleKeyword', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsClassDefinition', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'jsClassKeyword', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'jsExtendsKeyword', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'jsExportDefault', { fg = c.Blue, bg = 'NONE', bold = true })
    hl(0, 'jsFuncCall', { fg = c.Red, bg = 'NONE' })
    hl(0, 'jsObjectValue', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsParen', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsObjectProp', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsIfElseBlock', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsParenIfElse', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsSpreadOperator', { fg = c.Front, bg = 'NONE' })
    hl(0, 'jsSpreadExpression', { fg = c.Front, bg = 'NONE' })

    -- Typescript
    hl(0, 'typescriptLabel', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptExceptions', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptBraces', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptEndColons', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptParens', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptDocTags', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptDocComment', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'typescriptLogicSymbols', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptImport', { fg = c.Pink, bg = 'NONE', bold = true })
    hl(0, 'typescriptBOM', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptVariableDeclaration', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptVariable', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptExport', { fg = c.Pink, bg = 'NONE' })
    hl(0, 'typescriptAliasDeclaration', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'typescriptAliasKeyword', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptClassName', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'typescriptAccessibilityModifier', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptOperator', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptArrowFunc', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptMethodAccessor', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptMember', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'typescriptTypeReference', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'typescriptTemplateSB', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, 'typescriptArrowFuncArg', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptParamImpl', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptFuncComma', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptCastKeyword', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptCall', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptCase', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptReserved', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptDefault', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptDecorator', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'typescriptPredefinedType', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'typescriptClassHeritage', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'typescriptClassExtends', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptClassKeyword', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptBlock', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptDOMDocProp', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptTemplateSubstitution', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptClassBlock', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptFuncCallArg', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptIndexExpr', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptConditionalParen', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptArray', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'typescriptES6SetProp', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptObjectLiteral', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptTypeParameter', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'typescriptEnumKeyword', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptEnum', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'typescriptLoopParen', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptParenExp', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptModule', { fg = c.Front, bg = 'NONE' })
    hl(0, 'typescriptAmbientDeclaration', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptFuncTypeArrow', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptInterfaceHeritage', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'typescriptInterfaceName', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'typescriptInterfaceKeyword', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptInterfaceExtends', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptGlobal', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'typescriptAsyncFuncKeyword', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptFuncKeyword', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'typescriptGlobalMethod', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'typescriptPromiseMethod', { fg = c.Orange, bg = 'NONE' })

    -- XML
    hl(0, 'xmlTag', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'xmlTagName', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'xmlEndTag', { fg = c.Blue, bg = 'NONE' })

    -- Ruby
    hl(0, 'rubyClassNameTag', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'rubyClassName', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'rubyModuleName', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'rubyConstant', { fg = c.BlueGreen, bg = 'NONE' })

    -- Golang
    hl(0, 'goPackage', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'goImport', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'goVar', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'goConst', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'goStatement', { fg = c.Pink, bg = 'NONE' })
    hl(0, 'goType', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'goSignedInts', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'goUnsignedInts', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'goFloats', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'goComplexes', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'goBuiltins', { fg = c.Yellow, bg = 'NONE' })
    hl(0, 'goBoolean', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'goPredefinedIdentifiers', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'goTodo', { fg = c.Gray, bg = 'NONE' })
    hl(0, 'goDeclaration', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'goDeclType', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'goTypeDecl', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'goTypeName', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'goVarAssign', { fg = c.LightBlue, bg = 'NONE' })
    hl(0, 'goVarDefs', { fg = c.LightBlue, bg = 'NONE' })
    hl(0, 'goReceiver', { fg = c.Front, bg = 'NONE' })
    hl(0, 'goReceiverType', { fg = c.Front, bg = 'NONE' })
    hl(0, 'goFunctionCall', { fg = c.Yellow, bg = 'NONE' })
    hl(0, 'goMethodCall', { fg = c.Yellow, bg = 'NONE' })
    hl(0, 'goSingleDecl', { fg = c.LightBlue, bg = 'NONE' })

    -- Python
    hl(0, 'pythonStatement', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'pythonOperator', { fg = c.LightBlue, bg = 'NONE' })
    hl(0, 'pythonException', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'pythonExClass', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'pythonBuiltinObj', { fg = c.Front, bg = 'NONE' })
    hl(0, 'pythonBuiltinType', { fg = c.BlueGreen, bg = 'NONE' })
    hl(0, 'pythonBoolean', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'pythonNone', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'pythonTodo', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'pythonClassVar', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'pythonClassDef', { fg = c.BlueGreen, bg = 'NONE' })

    -- TeX
    hl(0, 'texStatement', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'texBeginEnd', { fg = c.Yellow, bg = 'NONE' })
    hl(0, 'texBeginEndName', { fg = c.LightBlue, bg = 'NONE' })
    hl(0, 'texOption', { fg = c.LightBlue, bg = 'NONE' })
    hl(0, 'texBeginEndModifier', { fg = c.LightBlue, bg = 'NONE' })
    hl(0, 'texDocType', { fg = c.Pink, bg = 'NONE' })
    hl(0, 'texDocTypeArgs', { fg = c.LightBlue, bg = 'NONE' })

    -- Git
    hl(0, 'gitcommitHeader', { fg = c.Gray, bg = 'NONE' })
    hl(0, 'gitcommitOnBranch', { fg = c.Gray, bg = 'NONE' })
    hl(0, 'gitcommitBranch', { fg = c.Pink, bg = 'NONE' })
    hl(0, 'gitcommitComment', { fg = c.Gray, bg = 'NONE' })
    hl(0, 'gitcommitSelectedType', { fg = c.Green, bg = 'NONE' })
    hl(0, 'gitcommitSelectedFile', { fg = c.Green, bg = 'NONE' })
    hl(0, 'gitcommitDiscardedType', { fg = c.Red, bg = 'NONE' })
    hl(0, 'gitcommitDiscardedFile', { fg = c.Red, bg = 'NONE' })
    hl(0, 'gitcommitOverflow', { fg = c.Red, bg = 'NONE' })
    hl(0, 'gitcommitSummary', { fg = c.Pink, bg = 'NONE' })
    hl(0, 'gitcommitBlank', { fg = c.Pink, bg = 'NONE' })

    -- Lua
    hl(0, 'luaFuncCall', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'luaFuncArgName', { fg = c.Front, bg = 'NONE' })
    hl(0, 'luaFuncKeyword', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'luaLocal', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'luaBuiltIn', { fg = c.Blue, bg = 'NONE' })

    -- SH
    hl(0, 'shDeref', { fg = c.Front, bg = 'NONE' })
    hl(0, 'shVariable', { fg = c.Front, bg = 'NONE' })

    -- SQL
    hl(0, 'sqlKeyword', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'sqlFunction', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'sqlOperator', { fg = c.Front, bg = 'NONE' })

    -- YAML
    hl(0, 'yamlKey', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'yamlConstant', { fg = c.Blue, bg = 'NONE' })

    -- Gitgutter
    hl(0, 'GitGutterAdd', { fg = c.Green, bg = 'NONE' })
    hl(0, 'GitGutterChange', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'GitGutterDelete', { fg = c.Red, bg = 'NONE' })

    -- Git Signs
    hl(0, 'GitSignsAdd', { fg = c.Green, bg = 'NONE' })
    hl(0, 'GitSignsChange', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'GitSignsDelete', { fg = c.Red, bg = 'NONE' })
    hl(0, 'GitSignsAddLn', { fg = c.Back, bg = c.Green })
    hl(0, 'GitSignsChangeLn', { fg = c.Back, bg = c.Yellow })
    hl(0, 'GitSignsDeleteLn', { fg = c.Back, bg = c.Red })

    -- NvimTree
    hl(0, 'NvimTreeRootFolder', { fg = c.Front, bg = 'NONE', bold = true })
    hl(0, 'NvimTreeGitDirty', { fg = c.Yellow, bg = 'NONE' })
    hl(0, 'NvimTreeGitNew', { fg = c.Green, bg = 'NONE' })
    hl(0, 'NvimTreeImageFile', { fg = c.Violet, bg = 'NONE' })
    hl(0, 'NvimTreeEmptyFolderName', { fg = c.Gray, bg = 'NONE' })
    hl(0, 'NvimTreeFolderName', { fg = c.Front, bg = 'NONE' })
    hl(0, 'NvimTreeSpecialFile', { fg = c.Pink, bg = 'NONE', underline = true })
    hl(0, 'NvimTreeNormal', { fg = c.Front, bg = opts.disable_nvimtree_bg and c.Back or c.LeftDark })
    hl(0, 'NvimTreeCursorLine', { fg = 'NONE', bg = opts.disable_nvimtree_bg and c.CursorDarkDark or c.LeftMid })
    hl(0, 'NvimTreeVertSplit', { fg = opts.disable_nvimtree_bg and c.SplitDark or c.Back, bg = c.Back })
    hl(0, 'NvimTreeEndOfBuffer', { fg = opts.disable_nvimtree_bg and c.CursorDarkDark or c.LeftDark })
    hl(
        0,
        'NvimTreeOpenedFolderName',
        { fg = 'NONE', bg = opts.disable_nvimtree_bg and c.CursorDarkDark or c.LeftDark }
    )
    hl(0, 'NvimTreeGitRenamed', { fg = c.GitRenamed, bg = 'NONE' })
    hl(0, 'NvimTreeGitIgnored', { fg = c.GitIgnored, bg = 'NONE' })
    hl(0, 'NvimTreeGitDeleted', { fg = c.GitDeleted, bg = 'NONE' })
    hl(0, 'NvimTreeGitStaged', { fg = c.GitStageModified, bg = 'NONE' })
    hl(0, 'NvimTreeGitMerge', { fg = c.GitUntracked, bg = 'NONE' })
    hl(0, 'NvimTreeBookmark', { fg = c.Green, bg = 'NONE' })
    hl(0, 'NvimTreeExecFile', { fg = c.Red, bg = 'NONE' })
    hl(0, 'NvimTreeOpenedFile', { fg = c.Front, bg = 'NONE' })
    hl(0, 'NvimTreeModifiedFile', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'NvimTreeGitDirty', { fg = c.GitModified, bg = 'NONE' })
    hl(0, 'NvimTreeGitNew', { fg = c.GitAdded, bg = 'NONE' })

    -- Bufferline
    hl(0, 'BufferLineIndicatorSelected', { fg = c.LeftDark, bg = 'NONE' })
    hl(0, 'BufferLineFill', { fg = 'NONE', bg = opts.transparent and c.Back or c.LeftDark })

    -- BarBar
    hl(0, 'BufferCurrent', { fg = c.Front, bg = c.TabCurrent })
    hl(0, 'BufferCurrentIndex', { fg = c.Front, bg = c.TabCurrent })
    hl(0, 'BufferCurrentMod', { fg = c.YellowOrange, bg = c.TabCurrent })
    hl(0, 'BufferCurrentSign', { fg = c.Front, bg = c.TabCurrent })
    hl(0, 'BufferCurrentTarget', { fg = c.Red, bg = c.TabCurrent })
    hl(0, 'BufferVisible', { fg = c.Gray, bg = c.TabCurrent })
    hl(0, 'BufferVisibleIndex', { fg = c.Gray, bg = c.TabCurrent })
    hl(0, 'BufferVisibleMod', { fg = c.YellowOrange, bg = c.TabCurrent })
    hl(0, 'BufferVisibleSign', { fg = c.Gray, bg = c.TabCurrent })
    hl(0, 'BufferVisibleTarget', { fg = c.Red, bg = c.TabCurrent })
    hl(0, 'BufferInactive', { fg = c.Gray, bg = c.TabOther })
    hl(0, 'BufferInactiveIndex', { fg = c.Gray, bg = c.TabOther })
    hl(0, 'BufferInactiveMod', { fg = c.YellowOrange, bg = c.TabOther })
    hl(0, 'BufferInactiveSign', { fg = c.Gray, bg = c.TabOther })
    hl(0, 'BufferInactiveTarget', { fg = c.Red, bg = c.TabOther })
    hl(0, 'BufferTabpages', { fg = c.Front, bg = c.TabOther })
    hl(0, 'BufferTabpagesFill', { fg = c.Front, bg = c.TabOther })

    -- IndentBlankLine
    hl(0, 'IndentBlanklineContextChar', { fg = c.ContextCurrent, bg = 'NONE', nocombine = true })
    hl(0, 'IndentBlanklineContextStart', { sp = c.ContextCurrent, bg = 'NONE', nocombine = true, underline = true })
    hl(0, 'IndentBlanklineChar', { fg = c.Context, bg = 'NONE', nocombine = true })
    hl(0, 'IndentBlanklineSpaceChar', { fg = c.Context, bg = 'NONE', nocombine = true })
    hl(0, 'IndentBlanklineSpaceCharBlankline', { fg = c.Context, bg = 'NONE', nocombine = true })

    -- LSP
    hl(0, 'DiagnosticError', { fg = c.Red, bg = 'NONE' })
    hl(0, 'DiagnosticWarn', { fg = c.Yellow, bg = 'NONE' })
    hl(0, 'DiagnosticInfo', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'DiagnosticHint', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'DiagnosticUnderlineError', { fg = 'NONE', bg = 'NONE', undercurl = true, sp = c.Red })
    hl(0, 'DiagnosticUnderlineWarn', { fg = 'NONE', bg = 'NONE', undercurl = true, sp = c.Yellow })
    hl(0, 'DiagnosticUnderlineInfo', { fg = 'NONE', bg = 'NONE', undercurl = true, sp = c.Blue })
    hl(0, 'DiagnosticUnderlineHint', { fg = 'NONE', bg = 'NONE', undercurl = true, sp = c.Blue })
    hl(0, 'LspReferenceText', { fg = 'NONE', bg = isDark and c.PopupHighlightGray or c.PopupHighlightLightBlue })
    hl(0, 'LspReferenceRead', { fg = 'NONE', bg = isDark and c.PopupHighlightGray or c.PopupHighlightLightBlue })
    hl(0, 'LspReferenceWrite', { fg = 'NONE', bg = isDark and c.PopupHighlightGray or c.PopupHighlightLightBlue })

    -- COC.nvim
    hl(0, 'CocHighlightText', { fg = 'NONE', bg = isDark and c.PopupHighlightGray or c.PopupHighlightLightBlue })
    hl(0, 'CocHighlightRead', { fg = 'NONE', bg = isDark and c.PopupHighlightGray or c.PopupHighlightLightBlue })
    hl(0, 'CocHighlightWrite', { fg = 'NONE', bg = isDark and c.PopupHighlightGray or c.PopupHighlightLightBlue })

    -- Nvim compe
    hl(0, 'CmpItemKindVariable', { fg = c.LightBlue, bg = 'NONE' })
    hl(0, 'CmpItemKindInterface', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'CmpItemKindText', { fg = c.LightBlue, bg = 'NONE' })
    hl(0, 'CmpItemKindFunction', { fg = c.Red, bg = 'NONE' })
    hl(0, 'CmpItemKindMethod', { fg = c.Red, bg = 'NONE' })
    hl(0, 'CmpItemKindKeyword', { fg = c.Front, bg = 'NONE' })
    hl(0, 'CmpItemKindProperty', { fg = c.Front, bg = 'NONE' })
    hl(0, 'CmpItemKindUnit', { fg = c.Front, bg = 'NONE' })
    hl(0, 'CmpItemKindConstructor', { fg = c.Orange, bg = 'NONE' })
    hl(0, 'CmpItemMenu', { fg = c.PopupFront, bg = 'NONE' })
    hl(0, 'CmpItemAbbr', { fg = c.Front, bg = 'NONE' })
    hl(0, 'CmpItemAbbrDeprecated', { fg = c.CursorDark, bg = c.PopupBack, strikethrough = true })
    hl(0, 'CmpItemAbbrMatch', { fg = isDark and c.LightBlue or c.DarkBlue, bg = 'NONE', bold = true })
    hl(0, 'CmpItemAbbrMatchFuzzy', { fg = isDark and c.LightBlue or c.DarkBlue, bg = 'NONE', bold = true })

    -- Dashboard
    hl(0, 'DashboardHeader', { fg = c.Blue, bg = 'NONE' })
    hl(0, 'DashboardDesc', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, 'DashboardIcon', { fg = c.YellowOrange, bg = 'NONE' })
    hl(0, 'DashboardShortCut', { fg = c.Pink, bg = 'NONE' })
    hl(0, 'DashboardKey', { fg = c.White, bg = 'NONE' })
    hl(0, 'DashboardFooter', { fg = c.Blue, bg = 'NONE', italic = true })

    if isDark then
        hl(0, 'NvimTreeFolderIcon', { fg = c.Front, bg = 'NONE' })
        hl(0, 'NvimTreeIndentMarker', { fg = c.LineNumber, bg = 'NONE' })

        hl(0, 'LspFloatWinNormal', { fg = c.Front, bg = 'NONE' })
        hl(0, 'LspFloatWinBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspInfoBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaHoverBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaSignatureHelpBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaCodeActionBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaDefPreviewBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspLinesDiagBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaRenameBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaBorderTitle', { fg = c.CursorDark, bg = 'NONE' })
        hl(0, 'LSPSagaDiagnosticTruncateLine', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaDiagnosticBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaDiagnosticBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaShTruncateLine', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaShTruncateLine', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaDocTruncateLine', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaRenameBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'LspSagaLspFinderBorder', { fg = c.LineNumber, bg = 'NONE' })

        hl(0, 'TelescopePromptBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'TelescopeResultsBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'TelescopePreviewBorder', { fg = c.LineNumber, bg = 'NONE' })
        hl(0, 'TelescopeNormal', { fg = c.Front, bg = 'NONE' })
        hl(0, 'TelescopeSelection', { fg = c.Front, bg = c.Selection })
        hl(0, 'TelescopeMultiSelection', { fg = c.Front, bg = c.PopupHighlightBlue })
        hl(0, 'TelescopeMatching', { fg = c.LightBlue, bg = 'NONE', bold = true })
        hl(0, 'TelescopePromptPrefix', { fg = c.Front, bg = 'NONE' })

        -- symbols-outline
        -- white fg and lualine blue bg
        hl(0, 'FocusedSymbol', { fg = '#ffffff', bg = c.UiBlue })
        hl(0, 'SymbolsOutlineConnector', { fg = c.LineNumber, bg = 'NONE' })
    else
        hl(0, 'NvimTreeFolderIcon', { fg = c.DarkBlue, bg = 'NONE' })
        hl(0, 'NvimTreeIndentMarker', { fg = c.TabOther, bg = 'NONE' })

        hl(0, 'LspFloatWinNormal', { fg = c.Front, bg = 'NONE' })
        hl(0, 'LspFloatWinBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspInfoBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaHoverBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaSignatureHelpBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaCodeActionBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaDefPreviewBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspLinesDiagBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaRenameBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaBorderTitle', { fg = c.CursorDark, bg = 'NONE' })
        hl(0, 'LSPSagaDiagnosticTruncateLine', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaDiagnosticBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaDiagnosticBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaShTruncateLine', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaShTruncateLine', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaDocTruncateLine', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaRenameBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'LspSagaLspFinderBorder', { fg = c.TabOther, bg = 'NONE' })

        hl(0, 'TelescopePromptBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'TelescopeResultsBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'TelescopePreviewBorder', { fg = c.TabOther, bg = 'NONE' })
        hl(0, 'TelescopeNormal', { fg = c.Front, bg = 'NONE' })
        hl(0, 'TelescopeSelection', { fg = '#FFFFFF', bg = c.PopupHighlightBlue })
        hl(0, 'TelescopeMultiSelection', { fg = c.Back, bg = c.PopupHighlightBlue })
        hl(0, 'TelescopeMatching', { fg = 'orange', bg = 'NONE', bold = true, nil })
        hl(0, 'TelescopePromptPrefix', { fg = c.Front, bg = 'NONE' })

        -- COC.nvim
        hl(0, 'CocFloating', { fg = 'NONE', bg = c.PopupBack })
        hl(0, 'CocMenuSel', { fg = '#FFFFFF', bg = '#285EBA' })
        hl(0, 'CocSearch', { fg = '#2A64B9', bg = 'NONE' })

        -- Pmenu
        hl(0, 'Pmenu', { fg = 'NONE', bg = c.PopupBack })
        hl(0, 'PmenuSel', { fg = '#FFFFFF', bg = '#285EBA' })

        -- symbols-outline
        -- white fg and lualine blue bg
        hl(0, 'FocusedSymbol', { fg = c.Back, bg = '#AF00DB' })
        hl(0, 'SymbolsOutlineConnector', { fg = c.TabOther, bg = 'NONE' })
    end
end

theme.link_highlight = function()
    -- Legacy groups for official git.vim and diff.vim syntax
    hl(0, 'diffAdded', { link = 'DiffAdd' })
    hl(0, 'diffChanged', { link = 'DiffChange' })
    hl(0, 'diffRemoved', { link = 'DiffDelete' })
    -- Nvim compe
    hl(0, 'CompeDocumentation', { link = 'Pmenu' })
    hl(0, 'CompeDocumentationBorder', { link = 'Pmenu' })
    hl(0, 'CmpItemKind', { link = 'Pmenu' })
    hl(0, 'CmpItemKindClass', { link = 'CmpItemKindConstructor' })
    hl(0, 'CmpItemKindModule', { link = 'CmpItemKindKeyword' })
    hl(0, 'CmpItemKindOperator', { link = '@operator' })
    hl(0, 'CmpItemKindReference', { link = '@parameter.reference' })
    hl(0, 'CmpItemKindValue', { link = '@field' })
    hl(0, 'CmpItemKindField', { link = '@field' })
    hl(0, 'CmpItemKindEnum', { link = '@field' })
    hl(0, 'CmpItemKindSnippet', { link = '@text' })
    hl(0, 'CmpItemKindColor', { link = 'cssColor' })
    hl(0, 'CmpItemKindFile', { link = '@text.uri' })
    hl(0, 'CmpItemKindFolder', { link = '@text.uri' })
    hl(0, 'CmpItemKindEvent', { link = '@constant' })
    hl(0, 'CmpItemKindEnumMember', { link = '@field' })
    hl(0, 'CmpItemKindConstant', { link = '@constant' })
    hl(0, 'CmpItemKindStruct', { link = '@structure' })
    hl(0, 'CmpItemKindTypeParameter', { link = '@parameter' })
end

return theme
